/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
val steamPath = providers.gradleProperty("steam.path").get()

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("gg.archipelago:Java-Client:latest.integration")

    implementation(files("${steamPath}/common/SlayTheSpire/desktop-1.0.jar"))
    implementation(files("${steamPath}/workshop/content/646570/1605060445/ModTheSpire.jar"))
    implementation(files("${steamPath}/workshop/content/646570/1605833019/BaseMod.jar"))
    implementation(files("${steamPath}/workshop/content/646570/1610056683/downfall.jar"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
