import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.gradleup.shadow") version "8.3.0"
}

description = "Archipelago Multi-World Integration into Slay the Spire"
version = "1.14"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
val steamPath = providers.gradleProperty("steam.path").get()

val provided by configurations.creating {
    extendsFrom(configurations.implementation.get())
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("gg.archipelago:Java-Client:latest.integration")

    shadow(files("${steamPath}/common/SlayTheSpire/desktop-1.0.jar"))
    shadow(files("${steamPath}/workshop/content/646570/1605060445/ModTheSpire.jar"))
    shadow(files("${steamPath}/workshop/content/646570/1605833019/BaseMod.jar"))
    shadow(files("${steamPath}/workshop/content/646570/1610056683/downfall.jar"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.processResources {
    filesMatching("ModTheSpire.json") {
        expand(project.properties)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<Copy>("deployLocal") {
    val mwJar = fileTree(project.layout.buildDirectory.dir("libs")).filter { f: File ->
        f.name.matches(Regex("ArchipelagoMW.*\\.jar"))
    }
    from(mwJar)
    into("${steamPath}/common/SlayTheSpire/mods/")
    dependsOn("shadowJar")
}